#
# conductor:ui - Conductor UI
#
# ===========================================================================================================
# 0. Builder stage
# ===========================================================================================================
FROM node:20.8.1-alpine AS builder

LABEL maintainer="Orkes OSS <oss@orkes.io>"

# Install the required packages for the node build
# to run on alpine
RUN apk update && apk add --no-cache python3 py3-pip make g++

# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app

# Copies package.json to Docker environment in a separate layer as a performance optimization
COPY ./ui/package.json ./

# Installs all node packages. Cached unless package.json changes
RUN yarn install && mkdir -p public && cp -r node_modules/monaco-editor public/ && yarn cache clean

# Copies everything else over to Docker environment
# node_modules excluded in .dockerignore.
COPY ./ui .

# Include monaco sources into bundle (instead of using CDN)
ENV REACT_APP_MONACO_EDITOR_USING_CDN=false

# ===========================================================================================================
# 1. Bin stage
# ===========================================================================================================
FROM node:20.8.1-alpine

LABEL maintainer="Orkes OSS <oss@orkes.io>"

# Copy compiled UI
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .

CMD [ "yarn", "start" ]
